### ISSUE TITLE
Add a project license

### ISSUE THREAD

**Issue by Calinou** [jprendes/service-worker-brotli#1]
The repository currently doesn't seem to contain any license. Could you add one, please? See [Choose a License](https://choosealicense.com/) for more information :slightly_smiling_face:

**Comment by jprendes** [comment]
Hi! The license is listed in `package.json` as `(MIT OR Apache-2.0)`.

**Comment by jprendes** [comment]
I've added the license files

**Comment by jprendes** [comment]
I've added the license files
